<<<<<<< HEAD
spring.application.name=service_reminder
=======
spring.application.name=usermanagement

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/car_service_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

>>>>>>> 0ad0e08b009de10eb84ca214eec4e2bb48dcb4fa
